const TEV_FRAMES=["/gotu/mirror-demo-v10/assets/tev-frame-01.png", "/gotu/mirror-demo-v10/assets/tev-frame-02.png", "/gotu/mirror-demo-v10/assets/tev-frame-03.png", "/gotu/mirror-demo-v10/assets/tev-frame-04.png"];
const ABOUT_PATHS=['/about-demo','/about-demo/flow','/about-demo/questions'];
let aboutStep=0;
let state=Model.initial(),view='about',focusId='reason',teamFilter='All teams',discussionStep=0,csvVisible=false,expandedSuggestion=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('#main');
const btn=(text,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const groupOrder=()=>['Looking back',...(state.identity?.teams||[]),'Looking forward'];
const approvalCount=()=>state.answers.filter(Model.isApproved).length;
const selected=()=>state.answers.find(a=>a.id===focusId);
const status=a=>`<span class="pill ${Model.isApproved(a)?'green':''}">${Model.isApproved(a)?'Approved':'Needs approval'} · version ${a.version}</span>`;
function dispatch(action){state=Model.reduce(state,action);render();}
const BASE="/gotu/mirror-demo-v10";
const SLUGS={back:'looking-back',Executive:'executive',GTM:'gtm',forward:'looking-forward'};
let routeSection=null,countdown=5,countdownTimer=null,micTimer=null,videoTimer=null,videoTick=0,videoPlaying=false,modalStep='',selectedOutput=null,historyRender=false,chatTurns=[];
const routePath=()=>view==='about'?BASE+ABOUT_PATHS[aboutStep]:view==='interview'?BASE+'/interview/'+(routeSection||SLUGS[state.chapters[state.chapter]?.id]||'looking-back'):BASE+({about:'/about-demo',outcomes:'/outcomes',tev:'/for-tev',group:'/group-brief',guide:'/interview-guide',initializing:'/initializing',start:'/start',voice:'/voice-guide',welcome:'/form',review:'/review',chat:'/chat',complete:'/copy',sheet:'/sheet'}[view]||'');
const locationPath=()=>location.protocol==='file:'?(location.hash.slice(1)||BASE):location.pathname.replace(/\/$/,'');
function writeRoute(replace=false){const path=routePath();if(locationPath()===path)return;const url=location.protocol==='file:'?'#'+path:path;history[replace?'replaceState':'pushState']({},'',url);}
function stopCountdown(){clearInterval(countdownTimer);countdownTimer=null;}
function stopMedia(){clearInterval(micTimer);clearInterval(videoTimer);micTimer=null;videoTimer=null;videoPlaying=false;}
function closeOnboarding(){stopMedia();modalStep='';const d=document.querySelector('#onboarding-dialog');if(d.open)d.close();}
function guardedView(v){if(['interview','review','outcomes','tev','group','guide','chat','complete','sheet'].includes(v)&&!state.identity){state.notice="Reloading clears this demo’s progress. Confirm your details in The Basics to begin again.";return 'welcome';}if(v==='review'&&!state.finished)return 'interview';if(['outcomes','tev','group','guide','chat','complete','sheet'].includes(v)&&!Model.currentPackage(state))return state.finished?'review':'interview';return v;}
function navigate(v,replace=false){if(state.editing){document.querySelector('#toast').textContent="Save or cancel your current edit first.";document.querySelector('#edit-text')?.focus();return;}stopCountdown();closeOnboarding();routeSection=null;view=guardedView(v);if(view==='initializing')countdown=5;writeRoute(replace);render();main.focus();window.scrollTo(0,0);if(view==='initializing')startCountdown();}
function startCountdown(){stopCountdown();countdownTimer=setInterval(()=>{if(view!=='initializing'){stopCountdown();return;}countdown--;if(countdown===0){navigate('start',true);return;}const n=document.querySelector('#countdown');if(n)n.textContent=countdown;},1000);}
function readRoute(){stopCountdown();closeOnboarding();const path=locationPath();const leaf=path.startsWith(BASE)?path.slice(BASE.length):'';const map={'':'about','/about-demo':'about','/outcomes':'outcomes','/for-tev':'tev','/group-brief':'group','/interview-guide':'guide','/initializing':'initializing','/start':'start','/voice-guide':'voice','/form':'welcome','/review':'review','/chat':'chat','/copy':'complete','/sheet':'sheet'};const framingStep=ABOUT_PATHS.indexOf(leaf);let target=framingStep>=0?'about':map[leaf];routeSection=null;if(leaf.startsWith('/interview/')){target='interview';routeSection=leaf.split('/')[2];}if(!target)target='about';if(state.editing&&target!==view){writeRoute(true);return;}if(target==='about')aboutStep=Math.max(0,framingStep);view=guardedView(target);if(view==='interview'&&routeSection){const n=state.chapters.findIndex(c=>SLUGS[c.id]===routeSection);if(n<0||n>state.chapter)routeSection=null;}historyRender=true;writeRoute(true);if(view==='initializing')countdown=5;render();historyRender=false;main.focus();window.scrollTo(0,0);if(view==='initializing')startCountdown();}
window.addEventListener('popstate',readRoute);
function render(){
 if(view!=='initializing')stopCountdown();
 if(!historyRender)writeRoute();
 document.querySelector('.shell').classList.toggle('ftue',['about','initializing','start','voice','welcome','outcomes','tev','group','guide','chat'].includes(view));
 const prior=document.activeElement?.closest('button[data-action]');const priorAction=prior?.dataset.action,priorId=prior?.dataset.id;
 const available=[['about','01','About this Demo'],['start','02','Participant Welcome'],['welcome','03','The Basics'],['interview','04','Mirror Interview'],['review','05','Review &amp; Submit'],['outcomes','06','Post-Submit Flow']];
 document.querySelector('#nav').innerHTML=available.map(([v,n,title])=>btn(`<span class="step-num">${n}</span>${title}`,'navigate',`data-view="${v}" ${((v==='interview'&&!state.identity)||(v==='review'&&!state.finished)||(['outcomes','tev','group','guide','chat','complete','sheet'].includes(v)&&!Model.currentPackage(state)))?'disabled':''} ${(view===v||(view==='answer'&&v==='review'))?'aria-current="step"':''}`)).join('');
 document.querySelector('#side-state').innerHTML=state.identity?`<p><strong>Demo subject: ${esc(state.identity.name)}</strong><br>Based on his 2026 Q2 submission.</p><p>${state.finished?`${state.answers.length} answers · ${Model.currentPackage(state)?'approved':'ready for review'}`:'Speak freely. You decide what gets shared.'}</p><p>${Model.currentPackage(state)?'Demo submission ready. Nothing sent.':'Review your answers, make changes, and approve the exact words the planning team receives.'}</p>`:'<p>Speak freely. You decide what gets shared.</p><p>Review your answers, make changes, and approve the exact words the planning team receives.</p>';
 main.innerHTML=({about:about,outcomes:outcomes,tev:forTev,group:groupBrief,guide:interviewGuide,initializing:initializing,start:startScreen,voice:voiceGuide,chat:afterChat,welcome:welcome,interview:interview,review:review,answer:answer,complete:complete,sheet:sheet}[view]||welcome)()+`<p id="toast" role="status" aria-live="polite">${esc(state.notice)}</p>`;
 updatePrint();
 const log=document.querySelector('.chat-scroll');if(log)log.scrollTop=log.scrollHeight;const personal=document.querySelector('.personal-log');if(personal)personal.scrollTop=personal.scrollHeight;
 if(priorAction){const target=[...main.querySelectorAll('button[data-action]')].find(b=>b.dataset.action===priorAction&&b.dataset.id===priorId&&!b.disabled);if(target)target.focus({preventScroll:true});}
}
function initializing(){return `<div class="initializing"><span class="eyebrow">GoTu · 2026 Q3 PreWork Mirror</span><h1>Starting the Mirror</h1><p class="lead">You’re about to experience the participant welcome.</p><div id="countdown" class="countdown" role="status" aria-live="polite">${countdown}</div><p class="small muted">The welcome opens automatically.</p>${btn("← Back to About this Demo",'navigate','data-view="about"','ghost')}</div>`;}
function startScreen(){return `<div class="welcome-editorial"><div class="experience-label"><strong>PARTICIPANT EXPERIENCE</strong> &gt; WELCOME</div><div class="welcome-hero"><div class="welcome-copy"><p class="eyebrow">Your GoTu PreWork Mirror</p><h1>Let’s talk about the quarter.<br><em>All of it.</em></h1><p class="lead">The wins. The friction. The things you’re still figuring out.</p><p>Take a moment to reflect on what happened and what matters next.</p>${btn('Get started','begin-onboarding','','primary')}<p class="tiny muted">First, a quick mic check, a few tips, and a welcome video.</p></div></div><div class="welcome-bottom"><p>After submitting, keep exploring a takeaway or a question you want to bring into the room.</p></div></div>`;}
function voiceGuide(){return `<div class="voice-guide-page"><div class="experience-label"><strong>PARTICIPANT EXPERIENCE</strong> &gt; VOICE GUIDE</div><div class="welcome-note mic-note"><span class="voice-symbol" aria-hidden="true">❙ ❚ ❙ ❚ ❙</span><p class="eyebrow">Write out loud</p><h2>Tell the story of your quarter. Out loud.</h2><p>The Mirror is designed for speaking. Thinking aloud can bring out details, connections, and thoughts you didn’t know were there.</p><h3>A few tips before you begin</h3><p><strong>1. You decide what gets shared.</strong></p><p>Speak freely. At the end, review all your answers and change anything you want. <strong>Your full transcript stays private. Only the words you approve go to the planning team.</strong></p><p><strong>2. Say more. Don’t edit yourself. Ramble!</strong></p><p>Pause, start again, or change your mind. The Mirror can help you follow a thought. You can make your answers clear during review.</p><p>We call this “blatherstorming.”</p><p><strong>3. Give yourself time.</strong></p><p>Choose a time when you can reflect without rushing or frequent interruptions.</p><p>Questions or concerns? Contact tev@joingotu.com.</p><div class="voice-guide-action"><span class="small">Next: a short welcome video.</span>${btn('Continue to video →','voice-next','','primary')}</div></div></div>`;}
function showOnboarding(html){const d=document.querySelector('#onboarding-dialog');d.innerHTML=html;if(!d.open)d.showModal();d.querySelector('button')?.focus();}
function openMic(){stopMedia();modalStep='mic';showOnboarding(`<button class="dialog-close ghost" data-action="close-onboarding" aria-label="Close mic check">×</button><p class="eyebrow">Before we begin</p><h2 id="dialog-title">Check your microphone</h2><p>Find a quiet place where you can speak freely. Headphones may help.</p><ol class="mic-steps"><li>Start the check.</li><li>Read the short phrase aloud.</li><li>Continue to the conversation tips.</li></ol><p class="notice small">This demo simulates the check. It won’t access your microphone or record you.</p>${btn("Start simulated mic check",'mic-test','','primary wide')}<div class="row spacer center">${btn("Skip mic check",'mic-skip','','ghost')}</div>`);}
function runMic(){stopMedia();modalStep='mic-running';showOnboarding(`<p class="eyebrow">Simulated mic check</p><h2 id="dialog-title">Try thinking out loud</h2><p>Read this at your own pace:</p><blockquote>I can take my time, think out loud, and choose what I share.</blockquote><div class="wave" aria-hidden="true">${Array.from({length:19},(_,i)=>`<i style="--bar:${12+(i%5)*5}px"></i>`).join('')}</div><p id="mic-state" class="small muted" role="status">Showing a simulated mic check…</p>${btn('Continue →','mic-stop','','primary wide')}`);micTimer=setTimeout(()=>{if(modalStep==='mic-running'){document.querySelector('#mic-state').textContent='Demo check complete. No audio was captured.';}},2500);}
const INTRO_COPY=['Make room for the detail behind your answers.','Talk about what’s working, what’s difficult, and what you want to change.','You’ll review everything and choose exactly what goes into planning.','Keep something useful for yourself: your takeaways and questions for the room.'];
function openVideo(){stopMedia();modalStep='video';videoTick=0;showOnboarding(`<button class="dialog-close ghost" data-action="close-onboarding" aria-label="Close welcome video">×</button><p class="eyebrow">PLACEHOLDER VIDEO &amp; CAPTIONS</p><p class="eyebrow">A welcome from your planning facilitator</p><h2 id="dialog-title">Your voice matters in planning.</h2><div class="tev-video"><img id="tev-frame" src="${TEV_FRAMES[0]}" alt="Planning facilitator in a still image"><span class="video-label">SILENT STILL SEQUENCE</span><p id="video-caption">${INTRO_COPY[0]}</p></div><div class="row between video-toolbar">${btn("▶ Play welcome video",'video-play','','small')}<span id="video-time" class="tiny muted">0:00 / 0:12</span></div><progress id="video-progress" max="12" value="0" aria-label="Welcome video playback"></progress><p class="tiny muted">Placeholder captions; no recorded speech.</p><div class="row between">${btn("Skip video",'video-next','','ghost')}${btn("Continue to The Basics →",'video-next','','primary')}</div>`);}
function toggleVideo(){if(videoPlaying){clearInterval(videoTimer);videoPlaying=false;}else{if(videoTick>=12)videoTick=0;videoPlaying=true;videoTimer=setInterval(()=>{if(modalStep!=='video'){stopMedia();return;}videoTick++;updateVideo();if(videoTick>=12){clearInterval(videoTimer);videoPlaying=false;updateVideo();}},1000);}updateVideo();}
function updateVideo(){const i=Math.min(3,Math.floor(videoTick/3));document.querySelector('#tev-frame').src=TEV_FRAMES[i];document.querySelector('#video-caption').textContent=INTRO_COPY[i];document.querySelector('#video-time').textContent='0:'+String(videoTick).padStart(2,'0')+' / 0:12';document.querySelector('#video-progress').value=videoTick;document.querySelector('[data-action="video-play"]').textContent=videoPlaying?'Ⅱ Pause':videoTick>=12?"↻ Replay welcome video":"▶ Play welcome video";}
document.querySelector('#onboarding-dialog').addEventListener('close',()=>{stopMedia();modalStep='';});
const OUTPUTS={brief:{prompt:"Help me prepare for the offsite",title:'What I want to bring into the room',body:`<p>Use these notes to decide what you want to explain, ask, or carry forward.</p><p class="tiny muted">Fixed example from the demo conversation; answer edits do not regenerate it.</p><h3>What I want to preserve</h3><p>This quarter held real momentum and serious frustration. A single rating should not flatten either side.</p><h3>What I want us to resolve</h3><p>A shared approach to AI building, governance, and prioritization—so we can move forward with confidence.</p><h3>A distinction worth making</h3><p>Wanting better evidence is compatible with acting now. We can agree on strategic bets while remaining honest about uncertainty.</p><h3>Questions to bring into the room</h3><ul><li>What agreement would remove the most friction around building with AI?</li><li>Which bets can we commit to now, and what evidence would change our minds?</li><li>How will we protect deep-work time while addressing the issues that need us together?</li></ul><h3>Leave room for a different view</h3><p>Where do my teammates see the situation differently? What might I be missing?</p><p class="small muted">Choose a question that fits what you want to understand. These examples do not change your submitted answers or create new commitments.</p>`},tension:{prompt:"Help me untangle a tension",title:'Better evidence, without standing still',body:"<p>The demo conversation holds two things at once: wanting clearer evidence and being ready to act. What would count as enough evidence for the next bet?</p><p class=\"small muted\">Fixed example from the demo conversation. It does not interpret your current edits.</p>"},question:{prompt:"Find my question for the room",title:"A question worth bringing to the offsite",body:'<p>“What shared agreement would let us move forward with confidence, even while some uncertainty remains?”</p><p>Read it aloud. Does it invite the conversation you want? Use it if it fits.</p><p class="small muted">Fixed example from the demo conversation; answer edits do not regenerate it.</p>'}};
function afterChat(){const p=Model.currentPackage(state);if(!p)return review();return `${branchBack()}<section class="evaluation-box"><p class="eyebrow">DEMO REVIEW · Participant follow-up</p><h2>Questions to consider</h2><ul><li>Which of these takeaways would you actually use before the offsite?</li><li>What would help you understand your reflection or say what matters more clearly?</li><li>Should the conversation remain available after submission? For how long?</li></ul></section><div class="personal-chat"><header class="personal-chat-heading"><div><p class="eyebrow">PARTICIPANT EXPERIENCE > AFTER SUBMISSION</p><h1>Your Mirror</h1></div><span class="small muted">Make the reflection useful to you</span></header><div class="personal-log" role="log" aria-label="Personal follow-up conversation" aria-live="polite"><p class="chat-receipt">✓ Submission approved <span>· Demo only: nothing sent</span></p><div class="bubble"><p class="speaker">MIRROR</p><p class="words">You’ve chosen what to share. What would help you walk into the offsite feeling prepared?<br><br>Pull out what matters most, put a tension into words, or find a question you want the room to explore.</p><p class="small muted">Your approved answers stay as you left them. This follow-up stays separate from your submission.</p></div>${chatTurns.map((id,i)=>{const o=id==='copy'?{prompt:'Show my approved answers',title:'Your approved answers',body:packageHtml(p,false)+`<div class="row">${btn('Print this copy','print','','small')}${btn("Review or change my answers",'navigate','data-view="review"','ghost small')}</div>`}:OUTPUTS[id];return `<section class="personal-turn" id="personal-turn-${i}"><div class="bubble cary"><p class="speaker">${mockLabel()}</p><p class="words">${esc(o.prompt)}</p></div><div class="bubble mirror-response"><p class="speaker">MIRROR</p>${id==='copy'?'':`<h2>${esc(o.title)}</h2>`}${o.body}</div></section>`}).join('')}</div><div class="personal-composer"><p class="small">Choose a starting point</p><div class="prompt-chips">${Object.entries(OUTPUTS).map(([id,x])=>btn(esc(x.prompt),'chat-output',`data-output="${id}"`)).join('')}${btn('Show my approved answers','chat-output','data-output="copy"')}</div><p class="tiny muted">The first three options show fixed examples from the demo conversation. “Show my approved answers” displays the exact copy you approved.</p></div></div>`;}
const MEETING_FRAMING = [{
 id:'V10-FRAMING-01',eyebrow:'Today’s walkthrough',title:'GoTu’s PreWork Mirror',
 lead:'A scripted, abbreviated example of the proposed experience.',
 context:'Based on Cary’s Q2 Executive and GTM input, with imagined follow-ups. This is not a new submission or approval from Cary. The email is fictional.',
 aimLabel:'Today’s aim',aim:'Review the proposed flow for this cycle—and identify what needs to change.'
}];
function meetingFraming(){
 const slide=MEETING_FRAMING[0];
 return `<section class="meeting-framing" data-copy-block="${slide.id}" aria-labelledby="framing-title"><p class="eyebrow">${esc(slide.eyebrow)}</p><h1 id="framing-title">${esc(slide.title)}</h1><p class="framing-scope">${esc(slide.lead)}</p><section class="framing-aim" aria-labelledby="framing-aim-title"><h2 id="framing-aim-title">${esc(slide.aimLabel)}</h2><p>${esc(slide.aim)}</p></section><p class="framing-context" data-copy-block="COPYBLOCK-010">${esc(slide.context)}</p><div class="framing-controls">${btn('View the flow →','framing-step','data-step="1"','primary')}</div></section>`;
}
function about(){return [meetingFraming,aboutFlow,questionsSlide][aboutStep]();}
function aboutFlow(){return `<section class="buyer-about prelude-flow"><p class="eyebrow">GoTu · 2026 Q3 PreWork Mirror demo</p><h1>How GoTu’s PreWork Mirror will flow</h1><ol class="functional-overview" aria-label="Stages of the PreWork Mirror"><li><div class="stage-marker"><span class="stage-number">1</span><span class="stage-label">Stage 1</span></div><strong>Welcome participants</strong><p>Introduce the Mirror and explain how participants control what stays private and what gets shared.</p></li><li><div class="stage-marker"><span class="stage-number">2</span><span class="stage-label">Stage 2</span></div><strong>Confirm the basics</strong><p>Confirm who’s taking part and which team offsites they’ll attend.</p></li><li><div class="stage-marker"><span class="stage-number">3</span><span class="stage-label">Stage 3</span></div><strong>Have the conversation</strong><p>Explore the existing planning questions, with follow-ups that invite detail and nuance.</p></li><li><div class="stage-marker"><span class="stage-number">4</span><span class="stage-label">Stage 4</span></div><strong>Review and approve</strong><p>Review all the answers, make changes, and approve exactly what the planning team receives.</p></li><li><div class="stage-marker"><span class="stage-number">5</span><span class="stage-label">Stage 5</span></div><strong>Use the results</strong><p>The proposed flow gives planners approved submissions and synthesized insights. Participants get their approved copy and a space to keep thinking.</p></li></ol><section class="flow-demo-notes rule" data-copy-block="COPYBLOCK-009" aria-labelledby="demo-notes-title"><h2 id="demo-notes-title">In this demo</h2><p><strong>Try editing an answer.</strong> After approval, your changes appear in this demo’s approved copy and spreadsheet preview. You can print the approved copy or download the CSV. Nothing is submitted.</p><p><strong>Examples stay fixed.</strong> The conversation, historical group themes, and example takeaways do not change. Resetting or reloading clears progress.</p></section><div class="prelude-controls">${btn('← Opening','framing-step','data-step="0"','ghost')}${btn('Questions to consider →','framing-step','data-step="2"','primary')}</div></section>`;}
function questionsSlide(){return `<section class="meeting-framing prelude-questions" data-copy-block="COPYBLOCK-008"><p class="eyebrow">During the walkthrough</p><h1>Questions to consider</h1><div class="prelude-question-list"><ul><li>Is the experience "fuller, faster, and funner" than last cycle’s form?</li><li>What background context would help?<ul><li>What are the tradeoffs of including someone’s previous submission, when available?</li><li>What are the tradeoffs of including EOS or other shared context?</li></ul></li><li>Does anything feel off-target or missing?</li><li>What should we consider for the next cycle?</li></ul></div><div class="prelude-controls">${btn('← The flow','framing-step','data-step="1"','ghost')}${btn('Begin demo →','launch-demo','data-copy-block="COPYBLOCK-007"','primary')}</div></section>`;}

function welcome(){return `<div class="basics-page"><p class="eyebrow">GoTu · 2026 Q3 PreWork Mirror</p><div class="onboard-progress"><span></span><span></span><span></span><span></span><span></span><span></span><small>The Basics</small></div><h1>Let’s start with the basics.</h1><p class="lead">Confirm your details and the team offsites you’ll attend.</p><form id="intake" class="card document"><h2>About you</h2><label for="name">Full name</label><input id="name" name="name" value="${esc(state.identity?.name||'Cary Gahm')}" required maxlength="200" ${state.identity?'disabled':''}><label for="email">Email address <span class="muted">(demo)</span></label><input id="email" name="email" type="email" value="${esc(state.identity?.email||'cary@example.com')}" required ${state.identity?'disabled':''}><fieldset ${state.identity?'disabled':''}><legend>Which team offsites will you attend?</legend><p class="tiny muted">The Q2 form includes all nine teams. This demo uses Executive and GTM.</p><div class="row" role="list" aria-label="Team offsites"><label class="team-chip" role="listitem"><input type="checkbox" name="team" value="Executive" ${!state.identity||state.identity.teams.includes('Executive')?'checked':''}>Executive</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Sales</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Marketing</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Operations</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>People Ops</label><label class="team-chip" role="listitem"><input type="checkbox" name="team" value="GTM" ${!state.identity||state.identity.teams.includes('GTM')?'checked':''}>GTM</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Finance</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Product</label><label class="team-chip demo-option" role="listitem" title="Included in the Q2 form; unavailable in this demo"><input type="checkbox" disabled>Engineering</label></div></fieldset><p class="tiny muted">Next, we’ll talk about last quarter, each team you selected, and what matters next.</p>${state.identity?btn('Start the Mirror','navigate','data-view="interview"','primary'):'<button class="primary" type="submit">Start the Mirror</button>'}</form></div>`;}
const MOCK_DETAIL="Scripted example based on Cary’s Q2 submission, with imagined follow-ups. This is not a new statement or approval from Cary.";
function mockLabel(staged=false){const detail=staged?'Filled by a demo shortcut. Based on Cary’s Q2 submission, with imagined follow-ups; not a new statement or approval from Cary.':MOCK_DETAIL;return `<span class="mock-label" tabindex="0" role="note" aria-label="${esc((staged?'Demo response filled by a shortcut. ':'Demo response. ')+'Based on Cary’s Q2 submission, with imagined follow-ups; not a new statement or approval from Cary.')}">DEMO RESPONSE <span class="mock-info" aria-hidden="true">i</span><span class="mock-tooltip" aria-hidden="true">${esc(detail)}</span></span>`;}
function interview(){
 if(!state.identity)return welcome();
 if(routeSection&&routeSection!==SLUGS[state.chapters[state.chapter]?.id]){const n=state.chapters.findIndex(c=>SLUGS[c.id]===routeSection);const names=state.chapters.slice(0,n+1).map(c=>c.name);return `<div class="conversation"><p class="eyebrow">Earlier in your conversation</p><h1>${esc(state.chapters[n]?.name||'Your interview')}</h1><p class="small muted">You’re viewing an earlier section. Your progress is saved for this demo session.</p>${transcriptHtml(state.transcript.filter(t=>names.includes(t.chapter)))}${btn('Continue where I left off →','navigate','data-view="interview"','primary')}</div>`;}
 if(state.finished)return `<p class="eyebrow">Conversation complete</p><h1>Your answers are ready to review.</h1><p class="lead">Read them through and change anything you want before approving what gets shared.</p>${btn('Review my answers →','navigate','data-view="review"','primary')}<div class="spacer">${transcriptHtml(state.transcript)}</div>`;
 const c=state.chapters[state.chapter],t=c.turns[state.turn];
 const phase=t?.final?'One final question':t?.closing?'Before we move on':'';
 const current=t?`<div class="bubble current-question" aria-label="Current Mirror question"><p class="speaker">MIRROR${phase?' · '+esc(phase.toUpperCase()):''}</p><p class="words">${esc(t.q)}</p></div>`:`<div class="bubble current-question"><p class="speaker">MIRROR</p><p class="words">${state.chapter===state.chapters.length-1?"Thank you. Let’s review your answers.":'Thank you. Let’s keep going.'}</p></div>`;
 const nextStep=state.chapter===0&&state.turn===0?`<div class="section-next" role="note"><p>Demo: choose “Show next turn” to play the next question and sample response. Continue until the next-section button appears.</p></div>`:'';
 return `<div class="conversation"><div class="row between"><h1>${esc(c.name)}</h1><span class="pill">Section ${state.chapter+1} of ${state.chapters.length}</span></div><p class="muted small">We’ll talk it through first. You’ll review all your answers at the end.</p>${nextStep}<div class="chapter-tabs" aria-label="Interview sections">${state.chapters.map((x,n)=>`<span class="${n===state.chapter?'current':''}">${n<state.chapter?'✓ ':''}${esc(x.name)}</span>`).join('')}</div><div class="chat-scroll" tabindex="0" aria-label="Interview transcript">${transcriptHtml(state.transcript)}${current}</div><div class="composer">${t?`<div class="row between">${btn('Show next turn →','respond','','primary')}<span class="tiny muted">Simulated conversation</span></div>`:btn(state.chapter===state.chapters.length-1?'Review all my answers →':'Continue to '+esc(state.chapters[state.chapter+1].name)+' →','next','','primary')}<details class="demo-controls"><summary>Demo shortcuts</summary><div class="stack"><p class="tiny muted">Skip ahead by filling the remaining answers with scripted examples.</p>${t?btn("Fill the rest of this section",'stage-section','','small'):''}${btn("Fill remaining answers and go to review →",'stage-all','','small')}</div></details></div></div>`;
}
function transcriptHtml(items){let prev='';return items.map(t=>{const divider=t.chapter!==prev?`<div class="chapter-divider">${esc(t.chapter)}</div>`:'';prev=t.chapter;return divider+`<div class="bubble"><p class="speaker">MIRROR${t.final?' · LAST FOLLOW-UP':t.closing?' · SECTION CLOSE':''}</p><p class="words">${esc(t.q)}</p></div><div class="bubble cary"><p class="speaker">${mockLabel(t.staged)}</p><p class="words">${esc(t.a)}</p></div>`;}).join('');}

let panelId=null,panelMode='view',panelInitial='';
const drawer=()=>document.querySelector('#answer-drawer');
function drawPanel(){
 const a=state.answers.find(x=>x.id===panelId);if(!a)return;const n=REVIEW_NOTES[a.id],d=discussionFor(a),editing=!!state.editing;
 drawer().innerHTML=`<header class="drawer-head"><div><p class="eyebrow">${esc(a.group)}</p><h2 id="drawer-title" tabindex="-1">${esc(a.label)}</h2></div>${btn('×','panel-close','aria-label="Close answer panel"','ghost')}</header><div class="drawer-body"><p class="question">${esc(a.question)}</p>${!editing?`<details class="current-wording" ${panelMode==='suggestion'?'':'open'}><summary>Answer to review</summary><div><p class="answer">${esc(a.text)}</p></div></details>${a.flag?`<section class="drawer-suggestion"><p class="eyebrow">Optional suggestion</p><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p>${btn("Use this as a starting point",'panel-use',`data-id="${a.id}"`,'primary')}<details class="spacer"><summary>Compare wording</summary><div><p class="answer">${esc(n.suggestion)}</p><p class="small muted">${esc(n.explanation)}</p></div></details>${btn('Keep my wording','panel-keep',`data-id="${a.id}"`,'ghost')}</section>`:''}<details class="answer-context"><summary>Conversation & original draft</summary><div><p class="small muted">Private context · not included in your submission</p><p class="answer">${esc(a.original)}</p>${transcriptHtml(state.transcript.filter(t=>t.fields.includes(a.id)))}${a.discussion.map(x=>`<p class="answer">${esc(x.question)}<br>${esc(x.response)}</p>`).join('')}</div></details>`:`${panelMode==='discuss'?`<div class="drawer-suggestion"><p class="eyebrow">Demo: scripted clarification</p><p>${esc(d.q)}</p>${discussionStep?`<p class="answer">${esc(d.a)}</p>`:btn('Show clarification','panel-clarify',`data-id="${a.id}"`)}</div>`:''}<label for="edit-text">Your answer</label>${editorControl(a,panelInitial)}<p class="tiny muted">Saving updates your answer. It doesn’t approve or submit it.</p>`}<p id="panel-status" role="status" class="small"></p></div><footer class="drawer-footer">${editing?`${btn('Save changes','panel-save',`data-id="${a.id}"`,'primary')}${btn('Cancel edit','panel-cancel','','ghost')}${panelMode==='edit'?btn('Talk it through','panel-discuss','','ghost small'):''}`:`${btn('Edit my answer','panel-edit',`data-id="${a.id}"`,'primary')}${btn('Talk it through','panel-discuss',`data-id="${a.id}"`,'ghost')}`}</footer>`;
}
function openPanel(id,mode='view'){panelId=id;panelMode=mode;drawPanel();drawer().showModal();document.querySelector('#drawer-title').focus();}
function beginPanelEdit(mode,text){const a=state.answers.find(x=>x.id===panelId);panelMode=mode;discussionStep=0;state=Model.reduce(state,{type:mode==='discuss'?'discuss':'edit',id:panelId});panelInitial=text??a.text;render();drawPanel();document.querySelector('#edit-text')?.focus();}
function closePanel(force=false){const input=document.querySelector('#edit-text');if(!force&&state.editing&&input&&input.value!==panelInitial&&!confirm("Discard your unsaved changes?"))return;const id=panelId;if(state.editing)state=Model.reduce(state,{type:'cancel'});drawer().close();panelId=null;render();document.querySelector('#answer-'+id+' button')?.focus({preventScroll:true});}
function branchBack(){return `<div class="branch-back">${btn("← Post-Submit Flow",'navigate','data-view="outcomes"','ghost')}<span class="tiny muted">Demo navigation</span></div>`;}
function outcomes(){const p=Model.currentPackage(state);return `<div class="outcome-page"><p class="eyebrow">DEMO OVERVIEW · After submission</p><h1>One reflection.<br>Two useful outcomes.</h1><p class="lead">The participant has reviewed and approved ${p.answers.length} answers. Explore what each side can use next.</p><p class="small muted">This overview is for demo review. Nothing has been sent.</p><div class="outcome-grid"><article><span class="eyebrow">01 · For the planning team</span><h2>Prepare the conversations that matter</h2><p>Read the approved answers, then explore an example of how group input can inform offsite discussion.</p><ul><li>Approved words in the familiar sixteen-column spreadsheet.</li><li>Historical group themes, differing views, and questions for the room.</li><li>A guide connecting the conversation to the existing planning questions.</li></ul>${btn('Explore the planning handoff →','navigate','data-view="tev"','primary')}</article><article><span class="eyebrow">02 · For the participant</span><h2>Bring something useful into the room</h2><p>Keep your approved answers and turn the reflection into preparation that matters to you.</p><ul><li>Pull out what you want to explain or ask.</li><li>Put a tension into words without losing either side.</li><li>Find a question worth bringing to the offsite.</li></ul>${btn("Explore the participant experience →",'navigate','data-view="chat"','primary')}</article></div><div class="rule"><p class="small muted">Try changing an approved answer. The demo will ask for fresh approval before creating a new submission.</p>${btn('Return to review','navigate','data-view="review"','ghost')}</div></div>`;}
function forTev(){return `${branchBack()}<p class="eyebrow">PLANNING TEAM · After submission</p><h1>What deserves time in the offsite?</h1><p class="lead">Start with what this participant approved. Then explore a historical example of group themes and questions. Consider what needs discussion, where views differ, and what you want to understand better.</p><section class="evaluation-box"><p class="eyebrow">DEMO REVIEW · Planning team</p><h2>Questions to consider</h2><ul><li>What would these outputs help you notice before the offsite?</li><li>Which topics would you want to understand better or bring into the room?</li><li>What is missing compared with how you prepare today?</li><li>Would talking with the approved submissions help? What would you ask?</li></ul></section><div class="outcome-grid three"><article><h2>Group themes & questions</h2><p>Look for recurring concerns, differing views, and questions that could open a useful discussion. This historical example does not analyze edits made in this demo.</p>${btn("Explore group themes →",'navigate','data-view="group"','primary')}</article><article><h2>Approved answers in a spreadsheet</h2><p>Read the participant’s approved words in each team’s context. Filter by team or download all approved values in the familiar format.</p>${btn("Review approved answers →",'navigate','data-view="sheet"','primary')}</article><article><h2>From form to conversation</h2><p>Check how the interview covers the familiar planning questions, with room for useful follow-ups.</p>${btn("Read the interview guide →",'navigate','data-view="guide"','primary')}</article></div><p class="small muted rule">The group briefing uses anonymized historical examples. It stays fixed when you edit this participant’s answers.</p>`;}
const GROUP_THEMES=[
 {title:"Clear decisions about building with AI",signals:'Across the group, related concerns appeared as requests for clearer permitted scope, risk checks, decision authority, and a reusable approval path. The inputs support a shared need for clarity, but not agreement on one control model.',question:'Walk one plausible AI proposal through the rules. Where could competent teams still reach different answers?',caution:'Do not reduce the input to “pro-AI” versus “anti-AI.” The group raised distinct operating questions.'},
 {title:"Who decides when views differ?",signals:'The group described circular issue discussions, defensive debate, unclear decision ownership, and uncertainty about whether the right issues reach the room. Other team input reported openness and cohesion, so the pattern is not a company-wide culture verdict.',question:'For one contested decision, who must agree, who must be heard, and who can commit us?',caution:'Separate the decision process from any interpersonal repair the specific issue may require.'},
 {title:"Choices that affect other teams",signals:'Across teams, people named parallel growth, product, efficiency, and campaign ambitions that can draw on the same capacity. The input identifies possible collisions and dependencies; it does not prove which initiative should win.',question:'If we protect this outcome, what will we do less of—and have the affected teams agreed?',caution:'Leave with an explicit tradeoff and a confirmed cross-team handoff, not another list of aspirations.'}
];
function groupBrief(){return `${branchBack()}<div class="group-brief"><p class="eyebrow">PLANNING TEAM · Historical group example</p><h1>Themes to explore together</h1><p class="lead">Use these example questions to consider what the room should discuss. Notice shared concerns and differences; a theme can matter without everyone agreeing.</p><div class="group-scope" aria-label="Historical example: contributors and teams"><div><strong>39</strong><span>contributors, anonymized</span></div><div><strong>54</strong><span>participant–team pairs</span></div><div><strong>9</strong><span>teams represented</span></div></div><div class="notice"><strong>Historical example · Not a finding about this cycle</strong><p>The example covers 55 historical submission rows. Names and individual wording are omitted here. It does not update when you edit the demo.</p></div>${GROUP_THEMES.map((theme,i)=>`<article class="theme-card"><p class="eyebrow">Group theme · ${String(i+1).padStart(2,'0')}</p><h2>${esc(theme.title)}</h2><p class="theme-signals"><strong>What the submissions suggest:</strong> ${esc(theme.signals)}</p><div class="facilitator-question"><span class="eyebrow">Ask in the room</span><p>“${esc(theme.question)}”</p></div><p class="small muted"><strong>Keep in mind:</strong> ${esc(theme.caution)}</p></article>`).join('')}<div class="row spacer">${btn('← Planning handoff','navigate','data-view="tev"','ghost')}${btn("View participant spreadsheet",'navigate','data-view="sheet"')}</div></div>`;}
const GUIDE=[
 ['Looking back','Personal Best','Personal best from the last 90 days','What’s one win outside work that meant a lot to you in the last 90 days?','If the significance is unclear: “What made that matter to you?”','One personal best; retain the 90-day window.'],
 ['Looking back','Professional Best','Professional best from the last 90 days','At work, what’s the win you’re most proud of from those 90 days?','If only an initiative is named: “What changed because of that?”','One work win; separate from personal best.'],
 ['Looking back','Quarter Rating; Rating Reason','Rate last quarter 1–10; biggest reason','What number would you give the quarter—1 is rough, 10 exceptional? What’s the biggest reason?','If the explanation complicates the number: “What would someone miss if they saw only the rating?”','Explicit whole number, 1–10. Preserve nuance in the separate reason; confirm discrepancies at review.'],
 ['Each selected team','EOS Component; EOS Example','EOS area needing improvement; one example','Thinking just about this team, which EOS area needs attention? What happened that brings it to mind?','Offer all six labels: Vision, People, Data, Issues, Process, Traction. Clarify the intended area if needed.','One selected EOS label and a distinct concrete example, per team.'],
 ['Each selected team','Avoided Conversation','Conversation the team may be avoiding','What does this team need to talk about that keeps getting left unsaid?','If the issue is named without the conversation: “What would you want the team to say out loud?”','Preserve the concern and intended discussion; do not soften disagreement automatically.'],
 ['Each selected team','Biggest Issue','Single biggest issue limiting the team','If you could name one thing holding this team back, what would it be?','If several compete: “Which is the biggest constraint right now?”','One priority issue, distinct for each team.'],
 ['Looking forward','Success Vision (90 days)','What would be true after a wildly successful quarter?','Picture us 90 days from now, with a quarter that went really well. What’s different?','If abstract: “What would you notice that tells you we got there?”','Person-level success vision, shared across team rows.'],
 ['Looking forward','Top Rock','Most important Rock to make that happen','To make that future happen, what’s the one Rock you’d put first?','If only a theme: “What would completing that look like?”','One proposed Rock. Do not invent an owner, deadline, or commitment.'],
 ['Looking forward','Issues List','Anything else for the Issues List','Before we finish, what else should go on the Issues List? Nothing else is a valid answer.','Clarify only if an item’s meaning is unclear.','Person-level list, or an explicit none; shared across team rows.']
];
function interviewGuide(){return `${branchBack()}<p class="eyebrow">PLANNING TEAM · Proposed interview guide</p><h1>The same questions.<br>Room for a conversation.</h1><p class="lead">Use this guide to cover the existing planning questions while giving people room to tell the story.</p><div class="guide-rules"><h2>How the conversation would work</h2><p>Confirm the participant’s basics. Talk about last quarter, each selected team, and what matters next. Build on what they’ve already said.</p><p>Ask one question at a time. Use follow-ups to clarify meaning or invite more detail. Near each section’s end, leave room for one final follow-up, then ask what else the team should understand.</p><p>Review the answers at the end. Participants can change the wording and approve exactly what gets shared. Preserve uncertainty and disagreement.</p><p class="tiny muted">The prompts below are examples, not a required script. They describe the proposed approach for this cycle; the demo conversation is scripted.</p></div>${GUIDE.map((r,i)=>`<article class="guide-entry"><p class="eyebrow">${esc(r[0])} · ${String(i+1).padStart(2,'0')}</p><h2>${esc(r[2])}</h2><div class="guide-columns"><div><p class="tiny muted">Example question</p><p class="guide-question">“${esc(r[3])}”</p><p class="small"><strong>Possible follow-up:</strong> ${esc(r[4])}</p></div><div><p class="tiny muted">What the approved answer should include</p><p>${esc(r[5])}</p><p class="small muted">Spreadsheet: ${esc(r[1])}</p></div></div></article>`).join('')}<section class="guide-rules"><h2>The same sixteen columns</h2><p>Submitted At records when the approved copy was created. Full Name, Email, and Teams come from The Basics. Team identifies each row. Four assessment fields vary by team; seven participant-level answers repeat across their team rows.</p><p class="small">${HEADERS.map(esc).join(' · ')}</p><p class="tiny muted">Based on GoTu’s Q2 prework form. Quarter labels change for this cycle; the 90-day windows stay the same.</p></section>${btn('Back to the planning handoff','navigate','data-view="tev"','ghost')}`;}

function review(){
 if(!state.finished)return interview();
 const notes=state.answers.filter(a=>a.flag),p=Model.currentPackage(state);
 return `<div class="review-document"><p class="experience-label">PARTICIPANT EXPERIENCE > REVIEW & SUBMIT</p><div class="review-intro"><p class="eyebrow">Your planning answers</p><h1>Make sure this says what you mean.</h1><p class="lead">Read through your answers. Open any answer to edit it or consider a suggestion.</p><p class="small muted"><strong>Only the words you approve, plus your name, email, and selected teams, go to the planning team. Your full transcript and review discussions stay private.</strong></p></div><section class="evaluation-box"><p class="eyebrow">DEMO REVIEW · Participant control</p><h2>Questions to consider</h2><ul><li>Is it clear what stays private and what gets shared?</li><li>Can participants review and change exactly what the planning team receives?</li><li>Does review provide enough control without feeling like extra work?</li></ul></section><div class="review-overview"><span><strong>${state.answers.length} answers</strong> · ${notes.length} ${notes.length===1?'suggestion':'suggestions'} to consider</span>${btn("Go to final approval ↓",'approval-anchor','','ghost small')}</div><div class="submission-paper"><div class="paper-meta"><strong>${esc(state.identity.name)}</strong><span>${esc(state.identity.teams.join(' · '))}</span><span class="small muted">${esc(state.identity.email)} · ${p?'Approved copy':'Ready for your review'}</span></div><nav class="review-jumps" aria-label="Review sections">${groupOrder().map((g,i)=>btn(esc(g),'jump-group',`data-group="group-${i}"`)).join('')}</nav>${groupOrder().map((group,i)=>`<section class="review-group" id="group-${i}"><h2>${esc(group)} <span class="tiny muted">· ${['Executive','GTM'].includes(group)?'This team':'Shared across teams'}</span></h2>${state.answers.filter(a=>a.group===group).map(answerCard).join('')}</section>`).join('')}</div><section class="review-finish" id="approval-section" tabindex="-1"><p class="eyebrow">Final approval</p><h2>Ready to share these answers?</h2><p>Approve the exact words shown here. You’ll receive a copy too.</p><label class="check"><input type="checkbox" id="all-reviewed"><span>I’ve reviewed these answers. They say what I want to share.</span></label><div class="row spacer">${btn("Approve my submission →",'approve-finish','id="approve-finish" disabled','primary')}</div><p class="tiny muted spacer">Demo only: nothing is sent. If you change an answer afterward, you’ll need to approve again.</p></section></div>`;
}
function answerCard(a){const label=Model.isApproved(a)?'Approved':a.choice;return `<article class="answer-card" id="answer-${a.id}" data-answer="${a.id}" tabindex="-1"><div class="answer-heading"><h3>${esc(a.label)}</h3><div class="row">${label?`<span>${esc(label)}</span>`:''}${btn('Edit','open-answer',`data-id="${a.id}" aria-label="Edit ${esc(a.label)} — ${esc(a.group)}"`,'ghost small')}</div></div><p class="answer">${esc(a.text)}</p>${a.id==='rating'?'<p class="tiny muted">1 — Rough · 10 — Exceptional</p>':''}${a.flag?btn('✧ '+esc(REVIEW_NOTES[a.id].title),'open-suggestion',`data-id="${a.id}"`,'suggestion-link'):''}</article>`;}

function editorControl(a,text){return a.kind==='rating'?`<input id="edit-text" type="number" min="1" max="10" step="1" value="${esc(text)}">`:a.kind==='component'?`<select id="edit-text">${EOS.map(x=>`<option ${text===x?'selected':''}>${x}</option>`).join('')}</select>`:`<textarea id="edit-text">${esc(text)}</textarea>`;}
function discussionFor(a){
 if(a.id==='GTM-example')return {q:'What should come through more clearly in this answer?',a:'I’m ready to move. I want to understand what is driving the results, and keep the uncertainty without making it sound like hesitation.',draft:DISCUSSION_DATA};
 if(a.id==='GTM-avoided')return {q:'What do you most want people to understand about “politicking”?',a:'Keep the concern about internal politics. I don’t mean “communicate better.” I want us to put this team first, agree on the bets, and go.',draft:POLITICS_REVISION};
 if(a.id==='reason')return {q:'How do you want to explain the difference between 6 and six and a half?',a:'Keep 6 on the whole-number scale. Explain that my overall feeling was six and a half. Don’t lose either the excitement or the frustration.',draft:RATING_REVISION};
 return {q:'What would you like to change or make clearer?',a:'I want to keep the meaning and edit the wording myself.',draft:a.text};
}
function answer(){return review();}
function renderAt(id){const before=document.querySelector('[data-answer="'+id+'"]')?.getBoundingClientRect().top;render();const card=document.querySelector('[data-answer="'+id+'"]');if(card&&before!==undefined)window.scrollBy(0,card.getBoundingClientRect().top-before);return card;}
function complete(){const p=Model.currentPackage(state);if(!p)return review();return `${branchBack()}<div class="completion"><div class="checkmark" aria-hidden="true">✓</div><p class="eyebrow">Your approved answers</p><h1>Keep the words you chose to share.</h1><p class="lead">Read or print your exact approved copy before the offsite. If you want to change an answer, return to review and approve again.</p><div class="notice success"><strong>Demo only · Nothing sent</strong><p class="small">${esc(p.identity.name)} · ${esc(p.identity.teams.join(' + '))}<br>${p.answers.length} approved answers · ${p.rows.length} spreadsheet rows</p></div><div class="row spacer">${btn('Print my approved copy','print','','primary')}${btn('Preview approved copy','preview-print')}${btn("Back to my Mirror",'navigate','data-view="chat"','ghost')}</div><details class="spacer"><summary>My approved answers</summary><div>${packageHtml(p,false)}</div></details><div class="rule"><p class="small muted">Need to change something? Editing an answer clears the current approval. Review and approve again to create an updated copy.</p>${btn("Return to review",'navigate','data-view="review"')}</div><div id="copy-preview"></div></div>`;}
function sheet(){const p=Model.currentPackage(state);if(!p)return review();const rows=p.rows.filter(r=>teamFilter==='All teams'||r[8]===teamFilter);return `${branchBack()}<p class="eyebrow">PLANNING TEAM · Spreadsheet preview</p><h1>Start with what they chose to share.</h1><p class="lead">Read the approved answers before deciding what needs follow-up or time in the offsite. Filter by team to see that team’s context; download the CSV to keep the approved values.</p><div class="notice"><strong>Demo preview · Nothing sent</strong><p>This spreadsheet includes approved answers, name, email, and selected teams. It excludes the conversation, rejected wording, and review notes.</p></div><div class="row between spacer"><div><label for="team-filter">Team</label><select id="team-filter"><option>All teams</option>${p.identity.teams.map(t=>`<option ${t===teamFilter?'selected':''}>${t}</option>`).join('')}</select></div><div class="row">${btn('Download CSV · all teams','csv','','primary')}${btn("View CSV text",'csv-preview')}</div></div><span class="tiny muted">${rows.length} of ${p.rows.length} rows · 16 columns · scroll horizontally →</span><div class="sheet-wrap" tabindex="0" aria-label="Approved spreadsheet"><table class="sheet"><thead><tr>${HEADERS.map((h,i)=>`<th scope="col">${String.fromCharCode(65+i)} · ${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td><p>${esc(v)}</p></td>`).join('')}</tr>`).join('')}</tbody></table></div>${csvVisible?`<label for="csv-text">CSV download contents</label><textarea id="csv-text" readonly>${esc(Model.csv(p))}</textarea>`:''}<div class="card"><p class="eyebrow">Facilitator preparation</p><h2>What might the group need to discuss?</h2><p>Explore historical examples of shared concerns and differing views, with questions you could bring into the room.</p>${btn("Explore historical group themes →",'navigate','data-view="group"','primary')}</div><div class="row spacer">${btn('← Planning handoff','navigate','data-view="tev"','ghost')}${btn("Change an answer and review approval again",'navigate','data-view="review"')}</div>`;}
function packageHtml(p,print){return `<h${print?'1':'2'}>GoTu · 2026 Q3 PreWork Mirror · Approved answers</h${print?'1':'2'}><p class="print-meta"><strong>DEMO ONLY · Nothing sent</strong><br>${esc(p.identity.name)} · ${esc(p.identity.email)}<br>Teams: ${esc(p.identity.teams.join('; '))}<br>Approved copy created: ${esc(p.at)}</p>${['Looking back',...p.identity.teams,'Looking forward'].map(g=>`<section class="print-section"><h2>${esc(g)}</h2>${p.answers.filter(a=>a.group===g).map(a=>`<div class="print-field"><h3>${esc(a.label)}</h3><p class="inline-text">${esc(a.text)}</p></div>`).join('')}</section>`).join('')}`;}
function updatePrint(){const p=Model.currentPackage(state);document.querySelector('#print-root').innerHTML=p?packageHtml(p,true):"<h1>No approved copy yet</h1><p>Review and approve your answers before printing. Your conversation and unapproved answers won’t be included.</p>";}
function stageSection(){if(state.finished)return;const c=state.chapters[state.chapter];while(state.turn<c.turns.length)state=Model.reduce(state,{type:'answer',staged:true});}
document.addEventListener('submit',e=>{if(e.target.id!=='intake')return;e.preventDefault();const f=new FormData(e.target);const teams=f.getAll('team');if(!f.get('name').trim()){document.querySelector('#toast').textContent='Enter a name.';return;}if(!teams.length){state.notice='Select at least one team.';const el=document.querySelector('#toast');el.textContent=state.notice;return;}state=Model.reduce(state,{type:'start',identity:{name:f.get('name').trim(),email:f.get('email').trim(),teams}});routeSection=null;view='interview';render();main.focus();window.scrollTo(0,0);});
document.addEventListener('change',e=>{if(e.target.id==='all-reviewed')document.querySelector('#approve-finish').disabled=!e.target.checked||!!state.editing;if(e.target.id==='team-filter'){teamFilter=e.target.value;render();}});
document.addEventListener('click',e=>{
 const b=e.target.closest('button[data-action]');if(!b||b.disabled)return;
 const action=b.dataset.action,id=b.dataset.id;

 if(action==='open-answer'||action==='open-suggestion'){openPanel(id,action==='open-suggestion'?'suggestion':'view');if(action==='open-answer')beginPanelEdit('edit');return;}
 if(action==='approval-anchor'){document.querySelector('#approval-section').scrollIntoView({block:'start'});document.querySelector('#approval-section').focus({preventScroll:true});return;}
 if(action==='panel-close'||action==='panel-cancel'){closePanel();return;}
 if(action==='panel-edit'){beginPanelEdit('edit');return;}
 if(action==='panel-discuss'){const input=document.querySelector('#edit-text');if(input&&input.value!==panelInitial&&!confirm("Discard your unsaved changes and view a scripted clarification?"))return;beginPanelEdit('discuss');return;}
 if(action==='panel-use'){beginPanelEdit('edit',REVIEW_NOTES[panelId].suggestion);return;}
 if(action==='panel-keep'){state=Model.reduce(state,{type:'keep',id:panelId});closePanel(true);return;}
 if(action==='panel-clarify'){const d=discussionFor(state.answers.find(a=>a.id===panelId));state=Model.reduce(state,{type:'clarification',id:panelId,question:d.q,response:d.a});discussionStep=1;panelInitial=d.draft;drawPanel();document.querySelector('#edit-text').focus();return;}
 if(action==='panel-save'){const text=document.querySelector('#edit-text').value,a=state.answers.find(x=>x.id===panelId);if(!Model.valid({...a,text})){document.querySelector('#panel-status').textContent='Enter an answer. Ratings must be whole numbers from 1 to 10.';return;}state=Model.reduce(state,{type:'save',id:panelId,text});closePanel(true);return;}
 if(action==='framing-step'){const step=Number(b.dataset.step);if(!Number.isInteger(step)||step<0||step>=ABOUT_PATHS.length)return;aboutStep=step;navigate('about');return;}
 if(action==='navigate'){if(b.dataset.view==='about'&&!state.editing)aboutStep=0;navigate(b.dataset.view);return;}
 if(action==='launch-demo'){if(state.identity&&!confirm("Start the walkthrough again? This clears your demo edits and approvals."))return;state=Model.initial();teamFilter='All teams';csvVisible=false;discussionStep=0;expandedSuggestion=null;selectedOutput=null;chatTurns=[];navigate('initializing');return;}
 if(action==='begin-onboarding'){openMic();return;}
 if(action==='mic-test'){runMic();return;}
 if(action==='mic-stop'||action==='mic-skip'){navigate('voice');return;}
 if(action==='voice-next'){openVideo();return;}
 if(action==='video-play'){toggleVideo();return;}
 if(action==='video-next'){closeOnboarding();navigate('welcome');return;}
 if(action==='close-onboarding'){closeOnboarding();return;}
 if(action==='chat-output'){if(!Model.currentPackage(state))return;chatTurns.push(b.dataset.output);render();const log=document.querySelector('.personal-log'),turn=log.querySelector('.personal-turn:last-child');if(turn)log.scrollTop+=turn.getBoundingClientRect().top-log.getBoundingClientRect().top-16;return;}
 if(action==='reset'){if(state.identity&&!confirm("Reset the demo? This clears your demo edits and approvals."))return;stopCountdown();closeOnboarding();routeSection=null;selectedOutput=null;chatTurns=[];state=Model.initial();view='about';aboutStep=0;teamFilter='All teams';csvVisible=false;discussionStep=0;expandedSuggestion=null;render();main.focus();window.scrollTo(0,0);return;}
 if(action==='respond'){dispatch({type:'answer'});return;}
 if(action==='stage-section'){stageSection();render();return;}
 if(action==='stage-all'){while(!state.finished){stageSection();state=Model.reduce(state,{type:'next'});}view='review';render();main.focus();window.scrollTo(0,0);return;}
 if(action==='next'){routeSection=null;state=Model.reduce(state,{type:'next'});if(state.finished)view='review';render();return;}
 if(action==='jump-answer'){document.querySelector('#answer-'+id)?.scrollIntoView({block:'start'});return;}
 if(action==='jump-group'){document.querySelector('#'+b.dataset.group)?.scrollIntoView({block:'start'});return;}
 if(action==='toggle-suggestion'){expandedSuggestion=expandedSuggestion===id?null:id;renderAt(id);return;}
 if(action==='keep'){state=Model.reduce(state,{type:'keep',id});expandedSuggestion=null;renderAt(id);return;}
 if(action==='edit'||action==='discuss'){if(state.editing)return;focusId=id;discussionStep=0;expandedSuggestion=null;state=Model.reduce(state,{type:action,id});renderAt(id);document.querySelector('#edit-text')?.focus({preventScroll:true});return;}
 if(action==='discuss-response'){discussionStep=1;const d=discussionFor(selected());state=Model.reduce(state,{type:'clarification',id,question:d.q,response:d.a});renderAt(id);return;}
 if(action==='save'){const text=document.querySelector('#edit-text').value;const a=state.answers.find(a=>a.id===id);if(!Model.valid({...a,text})){document.querySelector('#toast').textContent="Enter an answer. Ratings must be whole numbers from 1 to 10.";document.querySelector('#edit-text').focus();return;}state=Model.reduce(state,{type:'save',id,text});renderAt(id)?.focus({preventScroll:true});return;}
 if(action==='cancel'){state=Model.reduce(state,{type:'cancel'});renderAt(id)?.focus({preventScroll:true});return;}
 if(action==='suggest'){state=Model.reduce(state,{type:'edit',id});state=Model.reduce(state,{type:'save',id,text:REVIEW_NOTES[id].suggestion});expandedSuggestion=null;renderAt(id)?.focus({preventScroll:true});return;}
 if(action==='original'){state=Model.reduce(state,{type:'original',id});renderAt(id);return;}
 if(action==='approve'){dispatch({type:'approve',id});return;}
 if(action==='approve-finish'){
  if(!document.querySelector('#all-reviewed')?.checked||state.editing)return;
  state=Model.reduce(state,{type:'approveAll'});state=Model.reduce(state,{type:'package',at:new Date().toISOString()});
  if(Model.currentPackage(state)){selectedOutput=null;chatTurns=[];view='outcomes';render();main.focus();window.scrollTo(0,0);}return;
 }
 if(action==='package'){state=Model.reduce(state,{type:'package',at:new Date().toISOString()});if(Model.currentPackage(state)){selectedOutput=null;chatTurns=[];view='outcomes';render();main.focus();window.scrollTo(0,0);}return;}
 const p=Model.currentPackage(state);if(!p)return;
 if(action==='print'){updatePrint();window.print();return;}
 if(action==='preview-print'){document.querySelector('#copy-preview').innerHTML='<div class="card spacer">'+packageHtml(p,false)+'</div>';document.querySelector('#copy-preview').scrollIntoView({behavior:'instant'});return;}
 if(action==='csv-preview'){csvVisible=!csvVisible;render();return;}
 if(action==='csv'){const blob=new Blob([Model.csv(p)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='gotu-approved-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);state.notice="CSV downloaded. Nothing was sent to the planning team.";render();}
});
document.addEventListener('toggle',e=>{if(e.target.matches?.('.demo-controls')&&e.target.open)e.target.scrollIntoView({block:'nearest',behavior:'instant'});},true);
document.querySelector('#answer-drawer').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const d=drawer(),items=[...d.querySelectorAll('button,input,textarea,select,summary,a[href],[tabindex="0"]')].filter(x=>!x.disabled&&x.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement.id==='drawer-title')){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});
document.querySelector('#answer-drawer').addEventListener('cancel',e=>{e.preventDefault();closePanel();});
window.addEventListener('beforeprint',updatePrint);
readRoute();
